export const InjuryRecordData = {
  entityActivity: '',
  recordId: 0,
  employer: '',
  employerInfo: '',
  entity: '',
  insurance: '',
  name: '',
  birthDate: new Date(),
  personalNumber: 0,
  address: '',
  position: '',
  hoursWorked: 0,
  injuryDateTime: new Date(),
  injuryDescription: '',
  doctorVisit: false,
  alcoholTest: false,
  alcoholTestResult: '',
  injuryType: '',
  injuryCause: '',
  activity: '',
  location: '',
  injuryEventDescription: '',
  violation: '',
  preventionMeasures: '',
  witnessInfo: '',
  supervisor: '',
  numberOfInjuredPeople: 0,
  supervisorEmail: '',
  injuredBodypart: '',
  mainActivity: '',
  IC: '',
  mainActivityB: '',
  locationB: '',
  employerInfoB: '',
  ICB: '',
  deliveryAddress: '',
  nationality: '',
  From: new Date(),
  Until: new Date(),
  dateOfDeath: undefined,
  bodyPart: '',
  yearsWorked: 0,
  monthsWorked: 0,
  dayCount: 0,
}